version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "13:00"
    ignore:
      - dependency-name: "webpack"
        versions: ["5.x"]
    open-pull-requests-limit: 10
    versioning-strategy: increase
